### ISSUE TITLE
csl18n() isn't defined

### ISSUE THREAD

**Issue by henrywright** [bigwilliam/cornerstone-library-horizontal-scroller#4]
Hey bigwilliam

csl18n() seems to be undefined and is causing a fatal error.

See here for where it's called https://github.com/bigwilliam/cornerstone-library-carousel/blob/master/includes/csl-carousel/controls.php

Should the function name be csi18n?

**Comment by cobbman** [comment]
Hi @henrywright - just seeing this - I need to mark this repo as depreciated. The updated plugin is part of the PowerPack located here: https://github.com/d3fydev/cornerstone-powerpack

**Comment by cobbman** [comment]
Just updated the README to point to the new plugin location

**Comment by henrywright** [comment]
Thanks @bigwilliam
